config/routes.rb
Seatyourself::Application.routes.draw do

  get "categories/new"
  get "categories/show"
  get "categories/create"
  resources :restaurants do
    resources :reservations
  end

  resources :customers do
    resources :reservations

  end

  resources :sessions, :categories, :only => [:new, :create, :destroy]

  root :to => 'restaurants#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :restaurants
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_secure_password
	has_many :reservations
	has_many :restaurants, :through => :reservations
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :customer
	validates_numericality_of :num_of_customers, :greater_than => 2, :less_than => 21
	# validate :max_reservations

	# def max_reservations
	# 	if Reservation.sum(:num_of_customers) > 25
	# 		errors.add(:num_of_customers, "Restaurant is fully booked!")
	# 	end
	# end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates_numericality_of :capacity, :greater_than => 0, :less_than => 101
	has_many :reservations
	has_many :customers, :through => :reservations
	validates :name, :presence => true
	belongs_to :category

	def opening_hour
		07
	end

	def closing_hour
		20
	end

	def time_slots
		reservation_interval = 1.hour

		start_time = Time.zone.now + 10.minutes
		start_time = Time.zone.at((start_time.to_f / reservation_interval).ceil * reservation_interval)
		start_time = [start_time, start_time.change(hour: opening_hour)].max
		end_time = (start_time + 3.days).change(hour: closing_hour)

		all_times = []

		a_time = start_time

		begin

			all_times << a_time

			a_time += reservation_interval

			if (a_time + reservation_interval) > a_time.change(hour: closing_hour)
				a_time = (a_time + 1.day).change(hour: opening_hour)
			end
		end while a_time < end_time

		all_times
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_customer
  	@current_customer ||= Customer.find(session[:customer_id]) if session[:customer_id]
  end

  helper_method :current_customer

  def ensure_logged_in
  	unless current_customer
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  end
 end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  	@category = Category.new
  end

  def show
  	@category = Category.find(params[:id])
  end

  def create
  	@category = Category.new(category_params)
  	if @category.save
  		redirect_to new_category_path, :notice => "Successfully created a category"
  	else
  		render :action => :create
  	end
  end

  private
  def category_params
  	params.require(:category).permit(:cuisine)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
  	@customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
  	@customer = Customer.new(customer_params)
  	if @customer.save
  		redirect_to restaurants_url, :notice => "Signed up!"
  	else
  		render "new"
  	end
  end

  def show
    @customer = Customer.find(params[:id])
    @restaurants = current_customer.restaurants.all
    @reservations = current_customer.reservations.all
    # @reservation = current_customer.reservations.find(params[:id])
    # @restaurant = current_customer.restaurants.find(params[:id])
  end

  def index
    @reservations = current_customer.reservations.all
  end

  private

  def customer_params
  	params.require(:customer).permit(:first_name, :last_name, :email, :password, :password_confirmation, :telephone)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	before_filter :load_restaurant, except: [:index, :edit]
	# before_filter :load_customer, except: [:index, :create]

  def index
    if params[:customer_id]
      @object = Customer.find(params[:customer_id])
    elsif params[:restaurant_id]
      @object = Restaurant.find(params[:restaurant_id])
    end
    @reservations = @object.reservations.all
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def show
  	@reservation = Reservation.find(params[:id])
  	# @reservation = @customer.reservations.build(reservation_params)
  	# @reservation.customer_id = current_customer.id
  end

  def create
  	@reservation = @restaurant.reservations.build(reservation_params)
  	@reservation.customer_id = current_customer.id

  	if @reservation.save
  		redirect_to restaurants_path, notice: "Reservation successfully created"
  	else
  		render :action => :show
    end
  end

  def edit
  	@reservation = Reservation.find(params[:id])
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def destroy
  	@reservation = Reservation.find(params[:id])
  	@reservation.destroy
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update_attributes(reservation_params)
      redirect_to customer_path(current_customer)
    end
  end

  private
  def reservation_params
  	params.require(:reservation).permit(:day, :time, :num_of_customers, :restaurant_id, :customer_id)
  end

  def load_restaurant
  	@restaurant = Restaurant.find(params[:restaurant_id])
  end

  # def load_customer
  # 	@customer = Customer.find(params[:customer_id])
  # end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  	@restaurants = Restaurant.all
  end

  def new
  	@restaurant = Restaurant.new
  end

  def show
  	@restaurant = Restaurant.find(params[:id])

  	if current_customer
  		@reservation = @restaurant.reservations.build
  	end

  end

  def edit
  	@restaurant = Restaurant.find(params[:id])
  end

  def create
  	@restaurant = Restaurant.new(restaurant_params)
    @category = Category.new(restaurant_params)
  	if @restaurant.save
  		redirect_to restaurants_url
  	else
  		render :new
  	end
  end

  def update
  	@restaurant = Restaurant.find(params[:id])
  	if @restaurant.update_attributes(restaurant_params)
  		redirect_to restaurant_path(@restaurant)
  	end
  end

  private

  def restaurant_params
  	params.require(:restaurant).permit(:name, :address, :summary, :capacity, :image, :category_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	customer = Customer.find_by_email(params[:email])
  	if customer && customer.authenticate(params[:password])
  		session[:customer_id] = customer.id
  		redirect_to restaurants_url, :notice => "Logged in!"
  	else
  		render "new"
  	end
  end

  def destroy
  	session[:customer_id] = nil
  	redirect_to restaurants_url, :notice => "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nice_datetime(datetime)
			datetime.strftime("%A %B #{datetime.day.ordinalize} %Y, %l:%M %p").sub(/(\d)([a-z]+)/, '\1<sup>\2</sup>').html_safe

	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/new.html.erb
<h1>Create a new category</h1>

<%= form_for @category do |f| %>
	<%= f.label :cuisine %><br />
	<%= f.text_field :cuisine %>
	<%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

app/views/customers/index.html.erb
<h1><%= @customer.first_name %>'s Reservations</h1>

app/views/customers/new.html.erb
<h1>Sign Up!</h1>
<%= form_for @customer do |f| %>
	<div class="field">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name %>
	</div>

	<div class="field">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name %>
	</div>

	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :telephone %><br />
		<%= f.text_field :telephone %>
	</div>

	<div class="field">
		<%= f.submit %>
	</div>

	<% end %>

app/views/customers/show.html.erb
<%= link_to "Back to Restaurants", restaurants_url %>
<h1>Welcome, <%= @current_customer[:first_name] %>!</h1>
<h2>Below are your reservations:</h2>

<section><% @current_customer.reservations.each do |r| %>
	<%= link_to "Edit Reservation", edit_restaurant_reservation_path(r.restaurant.id, r.id) %>
	<strong>Restaurant:</strong> <%= r.restaurant.name %><br />
	<strong>Reservation time:</strong> <%= r.day %><br />
	<strong>Number of Guests:</strong> <%= r.num_of_customers %><br>
	<br>
	<% end %></section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="customerinfo">
	<% if current_customer %>
		Signed in as <%= current_customer.first_name %> | <%= link_to "My Profile", customer_path(current_customer) %> | <%= link_to "Log out", session_path("current"), :method => :delete %>
	<% else %>
		<%= link_to "Log in", new_session_path %>	or <%= link_to "Sign up", new_customer_path %>
	<% end %>
</header>

<div class="flash">
	<% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
	<% end %>
	<% if flash[:alert] %>
		<p id="alert"><%= flash[:alert] %></p>
	<% end %>

<%= yield %>


<%= params %>
</body>
</html>

app/views/reservations/edit.html.erb
<h1>Edit Your Reservation</h1>
<% if current_customer %>
<div class="reservation">
		<h3>Reservations</h3>
		<%= form_for([@restaurant, @reservation]) do |f| %>
			<div class="field">
				<%= f.label "When?" %><br />
				<%= f.datetime_select :day, order: [:month, :day] %>
			</div>

			<div class="field">
				<%= f.label "Number of Guests" %><br />
				<%= f.number_field :num_of_customers %>
			</div>
			<div class="actions">
				<%= f.submit %>
			</div>
		<% end %>
<% end %>

app/views/reservations/index.html.erb
<h1>Reservations for <%= @restaurant.name %></h1>
<% @reservations.each do |r| %>
	Customer: <%= r.customer.first_name %> <%= r.customer.last_name %><br />
	Reservation time: <%= r.day %><br />
	Number of Guests: <%= r.num_of_customers %><br />
<% end %>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reservations/show.html.erb
<h2>Here are your current reservations</h2>

app/views/restaurants/_form.html.erb
<%= form_for ([@category, @restaurant]) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

<div class="field">
	<%= f.label :address %><br />
	<%= f.text_field :address %>
</div>

<div class="field">
	<%= f.label :image %><br />
	<%= f.text_field :image %>
</div>

<div class="field">
	<%= f.label :category_id, "Cuisine" %>
	<%= f.collection_select :category_id, Category.all, :id, :cuisine%>
</div>

<div class="field">
	<%= f.label :capacity %>
	<%= f.number_field :capacity %>
</div>

<div class="field">
	<%= f.label :summary %><br />
	<%= f.text_area :summary %>
</div>

<div class="actions"><br />
	<%= f.submit %>
</div>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= link_to "Back to Restaurant", restaurant_path %>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<p><% @restaurants.each do |restaurant| %>
			<%= link_to restaurant[:name], "/restaurants/#{restaurant.id}" %><br />
			<%= restaurant[:category] %></p>
		<% end %>

app/views/restaurants/new.html.erb
<h1>Add a New Restaurant</h1>

<%= render 'form' %>

<%= link_to "Back to Restaurants", restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant[:name] %></h1>
<%= link_to "Back to Restaurants", restaurants_url %> | <%= link_to "Edit Restaurant", edit_restaurant_path %>
<% if current_customer %>
<div class="reservation">
		<h3>Reservations</h3>
		<%= form_for([@restaurant, @reservation]) do |f| %>
			<div class="field">
				<%= f.label :day, "When?" %><br />
				<%= f.select :day, @restaurant.time_slots.map{ |dt| [nice_datetime(dt), dt] } %>
			</div>

			<div class="field">
				<%= f.label "Number of Guests" %><br />
				<%= f.number_field :num_of_customers %>
			</div>
			<div class="actions">
				<%= f.submit %>
			</div>
		<% end %>
<% end %>
<br/>
<div>
	<section>
		<%= image_tag @restaurant[:image] %><br />
		<strong>Address:</strong> <%= @restaurant[:address] %><br />
		<strong>Category:</strong> <%= @restaurant[:category] %><br />
		<strong>Summary:</strong> <%= @restaurant[:summary] %><br />
	</section>
</div>